/**
 * Semantic clustering types for pain point grouping based on embedding similarity
 */

import type { Uuid } from "./database.types";

/**
 * A pain point with its embedding vector
 */
export interface PainPointEmbedding {
  painPointId: Uuid;
  description: string;
  embedding: number[];
}

/**
 * A member of a semantic cluster
 */
export interface ClusterMember {
  painPointId: Uuid;
  description: string;
  similarity: number; // Average similarity to other cluster members
}

/**
 * An edge in the similarity graph
 */
export interface SimilarityEdge {
  painPointA: Uuid;
  painPointB: Uuid;
  similarity: number;
}

/**
 * A semantic cluster formed by connected components
 */
export interface SemanticCluster {
  members: ClusterMember[];
  name?: string; // Generated by GPT after clustering
  description?: string; // Generated by GPT after clustering
}

/**
 * Configuration for semantic clustering
 */
export interface ClusteringConfig {
  similarityThreshold: number; // Default: 0.85
  minClusterSize: number; // Default: 1
}
