/**
 * Sprint 66: AI Venture Score Engine
 *
 * Types for venture_scores table.
 * All UUIDs are generated by the database. NO ID generation in AI.
 */

import type { Uuid } from "./decimal.types";

// ---------------------------------------------------------------------------
// Investment grade tiers (S&P-style, mapped to score bands)
// ---------------------------------------------------------------------------
export type InvestmentGrade =
  | "AAA"
  | "AA"
  | "A"
  | "BBB"
  | "BB"
  | "B"
  | "Reject";

// ---------------------------------------------------------------------------
// Recommendation tiers (deterministic — no AI)
// ---------------------------------------------------------------------------
export type VentureRecommendation =
  | "Strong Buy"
  | "Buy"
  | "Watch"
  | "Speculative"
  | "Reject";

// ---------------------------------------------------------------------------
// DB row shape (matches venture_scores table)
// ---------------------------------------------------------------------------
export interface VentureScoreRow {
  id: Uuid;
  opportunity_id: Uuid;
  overall_score: number;
  investment_grade: string;
  confidence_score: number;
  risk_score: number;
  roi_score: number;
  market_score: number;
  execution_score: number;
  innovation_score: number;
  financial_score: number;
  validation_score: number;
  forecast_score: number;
  research_score: number;
  recommendation: string;
  strengths: string[];
  weaknesses: string[];
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Insert payload — ids are NOT generated client-side.
// ---------------------------------------------------------------------------
export interface VentureScoreInsert {
  id?: Uuid;
  opportunity_id: Uuid;
  overall_score: number;
  investment_grade: string;
  confidence_score: number;
  risk_score: number;
  roi_score: number;
  market_score: number;
  execution_score: number;
  innovation_score: number;
  financial_score: number;
  validation_score: number;
  forecast_score: number;
  research_score: number;
  recommendation: string;
  strengths: string[];
  weaknesses: string[];
  created_at?: string;
  updated_at?: string;
}

// ---------------------------------------------------------------------------
// Aggregator input snapshot — what the calculator saw.
// Useful for debugging / audit log without re-deriving.
// ---------------------------------------------------------------------------
export interface VentureScoreComponents {
  validation: { available: boolean; score: number; confidence: number };
  forecast: { available: boolean; score: number; trend: number };
  financial: {
    available: boolean;
    overallScore: number;
    ltvCacRatio: number;
    breakEvenMonths: number;
  };
  research: { available: boolean; completeness: number; sources: number };
  insights: { available: boolean; quality: number };
  competition: { available: boolean; score: number };
  portfolio: { available: boolean; similarCount: number; avgPerformance: number };
  backtesting: { available: boolean; accuracy: number };
}

export interface VentureScoreDetail {
  row: VentureScoreRow;
  components: VentureScoreComponents;
  opportunityTitle: string;
}

// ---------------------------------------------------------------------------
// Dashboard / Admin views
// ---------------------------------------------------------------------------
export interface VentureScoreDashboardStats {
  total: number;
  average: number;
  gradeDistribution: Record<string, number>;
  recommendationDistribution: Record<string, number>;
  topByROI: number;
  topByConfidence: number;
  highestRisk: number;
  lowestRisk: number;
}

export interface VentureScoreListItem {
  id: Uuid;
  opportunity_id: Uuid;
  opportunity_title: string;
  overall_score: number;
  investment_grade: string;
  recommendation: string;
  confidence_score: number;
  risk_score: number;
  roi_score: number;
  created_at: string;
}
