/**
 * Mock AI Provider - returns fake responses for testing and development
 * This provider does not call any external AI service
 * 
 * NOTE: These are transient DTOs. IDs are generated by the database after insert.
 */

import type { AIProvider } from "@/types/ai";
import type {
  RawPostInput,
  PainPointInput,
  PainClusterInput,
  OpportunityInput,
  StartupIdeaInput,
} from "@/types/pipeline";

export class MockProvider implements AIProvider {
  /**
   * Extract pain points from raw posts - returns mock data
   */
  async extractPainPoints(posts: RawPostInput[]): Promise<PainPointInput[]> {
    const painPoints: PainPointInput[] = [];

    for (const post of posts) {
      // Generate 1-2 pain points per post based on content
      painPoints.push({
        pain: `Manual process causing errors and inefficiency`,
        category: "Operations",
        severity: 0.8,
        buying_intent: 0.7,
      });

      if (post.score && post.score > 80) {
        painPoints.push({
          pain: `Time-consuming task preventing focus on core business`,
          category: "Productivity",
          severity: 0.9,
          buying_intent: 0.85,
        });
      }
    }

    return painPoints;
  }

  /**
   * Cluster similar pain points - groups by category
   */
  async clusterPainPoints(
    painPoints: PainPointInput[],
  ): Promise<PainClusterInput[]> {
    const clusters = new Map<string, PainClusterInput>();

    for (const painPoint of painPoints) {
      const clusterName = painPoint.category;
      const existing = clusters.get(clusterName);

      if (existing) {
        // Cluster already exists
      } else {
        clusters.set(clusterName, {
          cluster_name: clusterName,
          description: `Pain points related to ${clusterName.toLowerCase()}`,
        });
      }
    }

    return Array.from(clusters.values());
  }

  /**
   * Generate opportunities from clusters - calculates scores
   */
  async generateOpportunities(
    clusters: PainClusterInput[],
  ): Promise<OpportunityInput[]> {
    return clusters.map((cluster, index) => {
      const frequency = 3 + index;
      const severity = 0.8 + index * 0.05;
      const buyingIntent = 0.7 + index * 0.1;
      const score = Math.round(
        (frequency * 10 + severity * 100 + buyingIntent * 100) / 3,
      );

      return {
        cluster_id: index.toString(), // Temporary - replaced by real UUID after insert
        title: `${cluster.cluster_name} Solution`,
        description: `AI-generated opportunity addressing: ${cluster.description}`,
        score,
        frequency,
        severity,
        buying_intent: buyingIntent,
      };
    });
  }

  /**
   * Generate startup ideas from opportunities - template-based
   */
  async generateStartupIdeas(
    opportunities: OpportunityInput[],
  ): Promise<StartupIdeaInput[]> {
    return opportunities
      .filter((opp) => opp.score > 70)
      .map((opportunity, index) => ({
        opportunity_id: index.toString(), // Temporary - replaced by real UUID after insert
        problem:
          "Businesses struggle with manual processes and inefficiency in this area",
        solution:
          `AI-Powered Solution ${index + 1} - Automated platform using machine learning`,
        mvp: "Simple web dashboard with AI assistant",
        pricing: "$99-$499/month SaaS subscription based on usage volume",
        customer: "Small and medium businesses with 10-100 employees",
        distribution: "SEO + Content Marketing + Reddit + Product Hunt",
        competitors: "Existing SaaS tools and manual workflows",
      }));
  }
}