-- Align pipeline_runs schema with code expectations.
--
-- Background:
--   Sprint 37 introduced embeddings generation in the pipeline and the
--   runner.service.ts started tracking `embeddings`, `averageClusterSize`
--   and `largestClusterSize` in PipelineRunResult. However, no migration
--   was written at the time, so the pipeline_runs table is missing those
--   columns. The "Run Pipeline" button on /dashboard fails with:
--
--     Failed to create pipeline run record:
--     Failed to create pipeline run:
--     Could not find the 'embeddings' column of 'pipeline_runs'
--     in the schema cache
--
--   This migration adds the three missing columns idempotently so the
--   existing pipeline_runs row shape (id, started_at, finished_at,
--   duration_ms, sources, raw_posts, pain_points, clusters,
--   opportunities, startup_ideas, status, created_at, error_message)
--   stays unchanged and the new fields become optional with sane
--   defaults that match what the runner inserts today.

ALTER TABLE public.pipeline_runs
  ADD COLUMN IF NOT EXISTS embeddings INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.pipeline_runs.embeddings IS
  'Number of pain-point embeddings generated by this pipeline run';

ALTER TABLE public.pipeline_runs
  ADD COLUMN IF NOT EXISTS average_cluster_size NUMERIC(10, 2);

COMMENT ON COLUMN public.pipeline_runs.average_cluster_size IS
  'Mean size (pain points per cluster) across clusters produced by this run';

ALTER TABLE public.pipeline_runs
  ADD COLUMN IF NOT EXISTS largest_cluster_size INTEGER;

COMMENT ON COLUMN public.pipeline_runs.largest_cluster_size IS
  'Size (pain point count) of the largest cluster produced by this run';
